### ISSUE TITLE
Error processing checkout. Please try again.

### ISSUE THREAD

**Issue by ensostyle** [wirecard/woocommerce-wcp#16]
all data added right, get this message

what to do and where to see debug log?

**Comment by rinnhofer** [comment]
Hello,
first of all you have to activate "Debug Log" in Wirecard Checkout Page plugin settings. Then you can find the specific log file in "Your_Wordpress_DIR/wp-content/uploads/wc-logs"

If you can't figure out the reason for the error according to your log you can contact "support@wirecard.at" for further help (If you do so, it is always helpfull to add the logfile to your request)

**Comment by ensostyle** [comment]
i checked and it dont produce log in folder ^(

**Comment by rinnhofer** [comment]
Sorry seems that the error appears before anything gets logged in our plugin.
There is too little information to help with your problem. Maybe you can check if you filled in all necessary  configuration :
https://guides.wirecard.com/shop_plugins:wcp:woocommerce:installation

If this doesn't solve your problem please contact our support, since there is no certain evidence according to your information that there is a technical problem with the plugin
